<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\ModuloSecretaria\Asignatura;
use App\Models\ModuloSecretaria\Facultad;

class AsignaturasSeeder extends Seeder
{
    public function run(): void
    {
        $data = [

            'Dirección Académica' => [
                'INV0205 - Metodología de la Investigación',
            ],

            'Dirección de Innovación y Emprendimiento' => [
                'EMP0402 - Emprendedores',
            ],

            'Facultad de Ciencias Administrativas y Económicas' => [
'ADM0222 - Gestión del Talento Humano',
'ADM0405 - Financial Strategy',
'ADM0467 - Corporate Strategy',
'CON0505 - Planeación Operativa',
'CON0803 - Estrategia Financiera',
'ADM0464 - Responsabilidad Social',
'ADM0410 - Contabilidad de Costos',
'ADM0110 - Principios de Administración',
'CON0701 - Auditoría Interna y Operacional',
'ADM0318 - Habilidades Gerenciales',
'ECO0503 - Econometría II',
'ADM0309 - Gestión de Recursos Humanos',
'ECO0502 - Macroeconomía I',
'ECO0703 - Desarrollo Económico',
'ADM0211 - Contabilidad de Costos I',
'ADM0308 - Finanzas II',
'NEI0204 - Gestión Ambiental en los Negocios Internacionales',
'NEI0409 - Inteligencia Comercial',
'ADM0106 - Teoría General de la Administración',
'ADM0404 - Liderazgo y Comportamiento Organizacional',
'ADM0109 - Contabilidad I',
'ADM0306 - Matemática Financiera',
'DRO0394 - Derecho Tributario',
'CON0403 - Gestión de Riesgo Empresarial I',
'CON0502 - Sistemas de Información Contable I',
'ADM0403 - Empresas Familiares',
'CON0709 - Fusiones y Adquisiciones',
'ADM0212 - Microeconomía',
'DRO0426 - Derecho Empresarial II',
'EC0101 - Culminación de Estudios',
'CON0303 - Contabilidad III',
'CON0602 - Auditoría II',
'DRO0425 - Derecho Empresarial I',
'ECO0701 - Banca y Economía Monetaria',
'ADM0115 - Office para Negocios',
'ECO0702 - Economía del Medio Ambiente',
'NEI0306 - Legislación y Gestión Aduanera',
'ADM0223 - Análisis Cuantitativo para la Gestión',
'ADM0312 - Finanzas',
'ADM0316 - Cultura de Servicio al Cliente',
'ADM0317 - Inteligencia de Negocios',
'NEI0406 - Contratación Internacional',
'CON0702 - Contabilidad Bancaria',
'NEI0102 - Política Comercial',
'ECO0102 - Principios de Economía',
'ECO0302 - Microeconomía I',
'NEI0309 - Comercio de Servicios',
'NEI0408 - Estrategias de Negociación',
'NEI0307 - Formulación y Evaluación de Proyectos de Exportación',
'NEI0407 - Cadenas de Valor',
            ],


            'Facultad de Ciencias Jurídicas. Humanidades y Relaciones Internacionales' => [
'HUM0106 - Sociología',
'DRO0520 - Introducción al Derecho I',
'DRO0610 - Derecho de Familia',
'LRI0103 - Fundamentos de Microeconomía',
'DRO0608 - Derecho Constitucional II (Parte Especial)',
'DROV0606 - Derecho Constitucional I (Parte General)',
'ADM0220 - Derecho Laboral y Seguridad Social',
'DROV0616 - Derecho de Obligaciones',
'DROV0622 - Derecho Mercantil II',
'DROV0642 - Derecho Tributario',
'DROV0636 - Técnicas de Oralidad y Litigación',
'DROV0615 - Derecho Penal II (Parte Especial)',
'DROV0639 - Deontología Jurídica',
'DRO0619 - Derecho Internacional Público',
'LRI0104 - Historia Moderna y Contemporánea',
'LRI0107 - Análisis de Multivariables',
'LRI0115 - Sistemas Políticos Comparados',
'DROV0520 - Introducción al Derecho I',
'LRI0106 - Introd. a las Relaciones Internacionales',
'LRI0121 - Organizaciones Internacionales I',
'RIN0101 - Introd. a las Relaciones Internacionales',
'LRI0119 - Seminario en Derecho Internacional',
'LRI0130 - Integración Centroamericana',
'DROV0612 - Derecho Administrativo II (Parte Especial)',
'DRO0630 - Sistema de Protección de los Derechos Humanos',
'DROV0628 - Derecho Comunitario',
'LRI0105 - Filosofía Política',
'DRO0609 - Derecho Penal I (Parte General)',
'DRO0631 - Derecho Procesal Penal II',
'DRO0645 - Práctica Profesional',
'DROV0625 - Derecho Procesal Penal I',
'DRO0611 - Derecho Administrativo I (Parte General)',
'DRO0618 - Derecho Mercantil',
'DRO0620 - Derecho de Contratos',
'DRO0640 - Derecho Notarial II',
'DRO0627 - Derecho de la Seguridad Social',
'DROV0626 - Derecho Laboral',
'DRO0629 - Práctica Procesal Civil',
'DROV0629 - Práctica Procesal Civil',
'DROV0627 - Derecho de la Seguridad Social',
'DRO0641 - Derecho de la Propiedad Intelectual',
'DRO0701 - Introducción al Estudio del Derecho',
'LRI0114 - Legislación Pública',
'LRI0120 - Relaciones Económicas Internacionales I',
'LRI0133 - Seminario en Economía Internacional',
'DRO0501 - Derecho Romano',
'DRO0502 - Historia del Estado y el Derecho',
'DRO0621 - Derecho de Sucesiones',
'DROV0617 - Derecho Procesal Civil I',
'DROV0640 - Derecho Notarial II',
'DRO0643 - Derecho Registral',
'LRI0112 - Geografía Política',
'DRO0644 - Derecho Bancario',
'DROV0614 - Derecho de Bienes',
'DROV0644 - Derecho Bancario',
'DROV0605 - Género y Poder',
'DROV0501 - Derecho Romano',
'DROV0643 - Derecho Registral',
'LRI0129 - Teoría y Práctica de Resolución de Conflictos',
'POL0302 - Política Ext. de Nicaragua y C.A. I',
'DROV0502 - Historia del Estado y el Derecho',
'DROV0604 - Teoría General del Estado',
'DROV0630 - Sistema de Protección de los Derechos Humanos',
'LRI0131 - Gestión Pública',
'LRI0141 - Análisis de Políticas Públicas',
'LRI0118 - Derecho Internacional Público II',
'LRI0123 - Inglés VII para Diplomacia y Relaciones Internacionales',

            ],


            'Facultad de Ciencias Médicas' => [
'SPU0321 - Metodología de Investigación',
'SPU0326 - Administración en Salud',
'MEI0325 - Toxicología',
'SPU0201 - Epidemiología',
'CBM0101 - Anatomía I',
'CNA0104 - Química Orgánica',
'CBM0238 - Histología I',
'PCL0221 - Patología I',
'CNA0211 - Biología Molecular y Celular',
'PSI0202 - Psicología General',
'PSI0209 - Psicología del Aprendizaje',
'PSI0218 - Prácticas Profesionalizantes en Intervención Educativa',
'MEI0319 - Dermatología',
'CBM0208 - Parasitología',
'MEI0328 - Genética',
'SPU0328 - Proyecto de Investigación',
'MEI0211 - Semiología I',
'MEI0333 - Medicina Interna',
'PCL0224 - Fisiopatología I',
'PSI0304 - Psiquiatría',
'MEI0327 - Imagenología',
'CBM0239 - Fisiología I',
'MEI0317 - Inmunología',
'CIR0309 - Oftalmología',
'ISCL006 - Introducción a la Semiótica Clínica',
'MEI0206 - Nutrición Clínica',
'MEI0332 - Medicina Legal y Legislación Médica',
'HUM0113 - Bioética',
'SPU0322 - Salud Comunitaria I',
'PSI0201 - Historia de la Psicología',
'CIR0311 - Cirugía',
'PSI0220 - Psicología Comunitaria',
'PSI0229 - Prácticas Profesionalizantes en Intervención Social',
'PSI0210 - Neurobiología de los Trastornos Mentales',
'PSI0217 - Evaluación Psicológica Clínica I',
'PSI0219 - Psicopatología II',
'MEI0326 - Medicina de Emergencia',
'PCL0225 - Farmacología Clínica I',
'GYO0305 - Ginecología y Obstetricia',
'CIR0312 - Práctica Hospitalaria Cirugía',
'CBM0241 - Historia de la Medicina',
'PED0305 - Pediatría',
'PSI0228 - Psicología Clínica y Psicoterapia II',
'PSI0221 - Evaluación Psicológica Laboral',
'PSI0208 - Psicología de la Personalidad',
'CIR0310 - Otorrinolaringología',
'SPU0331 - Medicina del Trabajo',
'PSI0101 - Psicología Médica',
'PSI0207 - Gestión del Talento Humano I',
'PSI0211 - Psicología del Desarrollo II',
'PSI0227 - Psicofarmacología',

            ],
            'Facultad de Ingeniería y Arquitectura' => [
'ADM0111 - Estadistica I',
'ADM0113 - Estadistica II',
'ARQ0376 - Taller de Diseño Urbano',
'ARQB0101 - Arquitectura Bioclimatica',
'CBI0201 - Dinamica',
'CEST0101 - Estructura I',
'CEST0103 - Estructura III',
'CIV0301 - Analisis Estructural I',
'CIV0310 - Geologia',
'CIV0312 - Hidrologia',
'CIV0314 - Ingenieria de Transporte',
'CIV0315 - Ingenieria Sanitaria',
'CIV0318 - Mecanica de Solidos',
'CIV0323 - Topografia',
'CNU0125 - Introduccion A la Programacion',
'CON0207 - Costos y Presupuesto',
'CPL0101 - Costo. Presupuesto y Licitacion de Obras',
'DIC0102 - Diseño de Concreto II',
'DT0101 - Dibujo Tecnico',
'FIS0101 - Fisica I',
'FIS0111 - Fisica Aplicada',
'GEO0101 - Geotecnia',
'HYTA0101 - Historia y Teoria de la Arquitectura I',
'HYTA0103 - Historia y Teoria de la Arquitectura III',
'IARQ0109 - Taller de Diseño Arquitectonico VII',
'ICV0101 - Introduccion a la Ingenieria Civil',
'IND0104 - Introduccion a la Ingenieria Industrial',
'IND0106 - Quimica',
'IND0203 - Procesos de Manufactura',
'IND0309 - Estudio del Trabajo',
'IND0310 - Ingenieria Economica',
'IND0311 - Control Estadistico de la Calidad',
'IND0313 - Produccion Mas Limpia',
'IND0408 - Gestion de la Calidad',
'IND0410 - Mecanica de Fluidos I',
'IND0411 - Seguridad E Higiene Ocupacional',
'IND0413 - Instalaciones Electricas',
'IND0414 - Investigacion de Operaciones I',
'IND0503 - Simulacion de Procesos',
'IND0505 - Energias Renovables',
'IND0507 - Gerencia de Proyecto',
'INGS0101 - Ingenieria Sismoresistente',
'ISE0101 - Instalaciones en Edificaciones',
'LEST0101 - Logica Estructural',
'LPA0101 - Logica Parametrica',
'MTM0103 - Calculo II',
'MTM0108 - Matematica Basica',
'MTM0202 - Ecuaciones Diferenciales Ordinarias',
'PCR0101 - Principio de Conservacion. Remodelacion y Restauracion del Patrimonio',
'PPR0102 - Practicas Profesionales II',
'SIS0108 - Algoritmos y Estructuras de Datos',
'SIS0110 - Introduccion a las TIC',
'SIS0211 - Administracion y Gestion de Bases de Datos',
'SIS0212 - Programacion Orientada A Objetos II',
'SIS0312 - Analisis y Diseño Orientado A Objetos',
'SIS0313 - Tecnologia de Redes I',
'SIS0401 - Ingenieria de Software I',
'SIS0403 - Almacen de Datos',
'SIS0407 - Auditoria Informatica',
'SIS0416 - Diseño Web y Comercio Electronico',
'SIS0422 - Administracion y Gestion de Proyecto',
'SIS0505 - Reingenieria de Procesos',
'SIS0506 - Simulacion de Sistemas',
'STC0101 - Sistemas Constructivos I',
'TARQ0101 - Diseño Arquitectonico I',
'TARQ0103 - Diseño Arquitectonico III',
'TARQ0105 - Diseño Arquitectonico V',
'TARQ0107 - Diseño Arquitectonico VII',
'TDAR0102 - Taller Digital Arquitectonico II',
'URBA0103 - Urbanismo y Ambiente III',
            ],


            'Facultad de Marketing. Diseño y Ciencias de la Comunicación' => [
'COM0103 - Fundamentos de la Comunicacion y las RRPP',
'COM0403 - Fotografia Editorial',
'COM0513 - Gestion de Eventos y Protocolo',
'CYL0101 - Comunicacion y Lenguaje I',
'CYL0102 - Comunicacion y Lenguaje II',
'DIS0214 - Fotografia Publicitaria',
'DIS0220 - Arte Interpretativo',
'DIS0222 - Principios de Marketing',
'DIS0224 - Redaccion Publicitaria',
'DIS0319 - Investigacion Contextual',
'DIS0421 - Produccion de Eventos',
'DIS0422 - Produccion Cinematografica',
'MAR0106 - Fundamentos de Marketing',
'MAR0109 - Teoria de la Comunicacion Publicitaria',
'MAR0212 - Estrategia de la Comunicacion Promocional',
'MAR0213 - Comunicacion Publicitaria: Tradicional y Digital',
'MAR0311 - Investigacion de Mercados',
'MAR0325 - Oratoria y Negociacion',
'MAR0328 - Redes Sociales y Marketing Electronico',
            ],

            'Facultad de Odontología' => [
'CBM0225 - Fisiologia Humana',
'CBM0227 - Bioquimica',
'CBM0228 - Histoembriologia',
'CBM1313 - Anatomia Humana I',
'CBO0210 - Materiales Dentales I',
'CBO0221 - Educacion Sanitaria',
'CBO1220 - Introduccion A la Odontologia',
'MCO0305 - Cirugia Oral IV',
'MCO0311 - Anestesiologia',
'MCO0312 - Radiologia',
'MCO0317 - Patologia Oral II',
'OCL0346 - Oclusion II',
'ODO0349 - Odontologia Digital',
'ODR0327 - Preclinica de Operatoria Dental',
'ODR0329 - Clinica de Endodoncia',
'ODR0330 - Preclinica de Protesis Parcial Fija',
'ODR0335 - Clinica de Odontopediatria',
'ODR0336 - Clinica de Protesis Total',
'ODR0337 - Preclinica de Ortodoncia',
'ODR0338 - Clinica Integral',
'ODR0339 - Clinica de Protesis Parcial Removible',
'ODR0343 - Operatoria Dental II',
'ODR0347 - Periodoncia II',
'OPS1308 - Odontologia Preventiva',
'PCL1218 - Patologia General',
'PCL1219 - Farmacologia Basica',
'PSI0202 - Psicologia en Odontologia',
'SPU0317 - Epidemiologia',

            ],
            'Language Center' => [
                'CEP0001 - A1 Communicative English',
                'CEP0003 - A2+ Communicative English',
                'CEP0005 - B1+ Communicative English',
            ],
            
            'Vida Estudiantil' => [
                'PIU0101 - Proyeccion e Integracion Universitaria',
            ],
        ];

        foreach ($data as $facultadNombre => $asignaturas) {
            $facultad = Facultad::firstOrCreate(['nombre' => $facultadNombre]);
            foreach ($asignaturas as $nombre) {
                Asignatura::firstOrCreate([
                    'nombre' => $nombre,
                    'facultad_id' => $facultad->id,
                ]);
            }
        }
    }
}