<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ModuloSecretaria\Docente;
use App\Models\User;
use App\Models\ModuloSeguridad\Role;
use Illuminate\Support\Str;

class DocentesSeeder extends Seeder
{
    public function run(): void
    {
        $docenteNames = [
'Neylia Lidiadel Abboud Castillo',
'Jose Angel Acacio Laurens',
'Maria Delos Angeles Acevedo Delgadillo',
'Karla Del Rosario Acosta Mora',
'Edwin Javier Acuña Quintanilla',
'Ana Jose Aguilar Arriola',
'Jose Aguilar Escorcia',
'Fernando Noel Aleman Ruiz',
'Alexis Josué Alonzo Martínez',
'Romer Altamirano Guerrero',
'Dorwin Erick Altamirano Gutierrez',
'Francia Elena Alvarado Meza',
'Gilda Alvarado Reyes',
'Ivania Alvarez Bendaña',
'Fanny Del Socorro Alvarez Cruz',
'Francisco Arauz Rodriguez',
'Mario Alberto Arauz Torres',
'Geraldine Marielo Arce Vanegas',
'Juan Carlos Areas Suarez',
'Milton  Arguello Arguello',
'Carlos Ivan Arguello Martinez',
'Leyla Maria Arguello Montiel',
'Efrain De Jesus Artola Flores',
'Nestor Manuel Avendaño Castellon',
'Fanor Angel Avendaño Soza',
'Ileana Averruz Hawkins',
'Sara Fabiola Aviles Urtecho',
'Erika Jose Baez Laguna',
'Christopher Alberto Baldizón Tinoco',
'Eddy German Balladares Quintero',
'Luvy Jeronima Barquero Vega',
'Lubin Orlando Barrera Rodriguez',
'Wildghem Ramon Benavides Rodriguez',
'Yara Bendaña',
'Freddy Berrios Vega',
'Virgilio Humberto Blandon Membreño',
'Katherin Blandon Rivas',
'Mayela Jose Blas Calero',
'Gerardo Guillermo Blass Alfaro',
'Juditht Albania Bolaños Morales',
'Roxana Natalia Bone Davila',
'Ernesto Bone Zapata',
'Jose Bonilla Alvaro',
'Angelarrosa Bonilla Sanchez',
'Max Ali Bravo Gadea',
'Marisela Del Socorro Brenes Chamorro',
'Karen Anielka Briones Moreno',
'Darwin Joel Cajina Carillo',
'Mauricio Alfredo Cajinas Santos',
'Eduardo Andres Calderon Marenco',
'Walter Emilio Campos Blanco',
'Jairo Baltazar Campos Valerio',
'Maria Jose Canales Pereira',
'Shirley Carballo Diaz',
'Paola Giovannia Carcache Silva',
'Violeta Margarita Cardenas Calero',
'Ena Maria Casaya Rodriguez',
'Norman Jose Cash Arcia',
'Claudia Castillo Chavarria',
'Vanessa Castillo Galdamez',
'Erick Antonio Castillo Gurdian',
'Cinthia Lilieth Castillo Hurtado',
'Michael Andres Castillo Sandoval',
'Indira Karina Castrillo Cruz',
'Cesar Castro Espinoza',
'Guillermo Ivan Castro Iraheta',
'Flavia Isabel Castro Romero',
'Maria Mercedes Castro Sanchez',
'Elizabeth Del Socorro Castro Santamaria',
'Zoila Castro Urbina',
'Engels Darien Cañas Gago',
'Miriam Del Socorro Cerda Cea',
'Jury Martin Cerda Flores',
'Yader Yacir Cerda Sanchez',
'Andrea Maria Ceron Almendarez',
'Jairo Cerrato Gonzalez',
'Luis Chacon Reyes',
'Hernaldo Jose Chamorro Diaz',
'Jorge Adolfo Chamorro Flores',
'Jose Ariel Chavarria Hernandez',
'Sergio Cordero',
'James Cordonero Cordoba',
'Juan Edgard Corea Gallo',
'Marvin Corrales Perez',
'Alicia Guadalupe Cortez Raudes',
'Marines Cruz Montoya',
'Kenia De Jesus Cruz Ruiz',
'Jose Tomas Davila Arriola',
'Kiara Julieth Davila Ramirez',
'Melissa Daniela Davila Solano',
'Mirna Del Carmen Delgado ',
'Carmen Maria Diaz Gutierrez',
'Ricardo Humberto Diaz Jaen',
'Marcia Elena Doña Nicaragua',
'Zacarias Duarte Castellon',
'Karla Valeria Duarte Manzanares',
'Jose Duran Garcia',
'Hugo España M. ',
'Ondina Elena Espinal Espinoza',
'Luis Javier Espinoza Hernández',
'Martha Espinoza Hurtado',
'Manuel Espinoza Jarquin',
'Annysabell Espinoza Lopez',
'Eymi Lissette Esquivel Avendaño',
'Alicia Auxiliadora Estrada Castillo',
'Alvaro Rene Estrada Gonzalez',
'Noel Antonio Estrada Gutierrez',
'Diana Vanessa Figueroa Flores',
'Xochilth Del Carmen Fley Centeno',
' Jose Santos Flores',
'Kenneth Joel Fonseca Lupiac',
'Veronica Elizabeth Gaitan Muñoz',
'Maria Del Socorro Gaitan Nicolas',
'Lesther Gallo Pastran',
'Martha De Los Angeles Galo Pacheco',
'Tobias Adrian Gamboa Solano',
'Adriana De Jesus Garcia',
'Leonel Antonio Garcia',
'Alejandra Melissa Garcia Alvarez',
'Jose Daniel Garcia Estrada',
'Silvia Elisa Garcia Hueck',
'Marcia Azucena Garcia Mendoza',
'Porfirio Elias Garcia Romano',
'Mauricio Antonio Garcia Sotelo',
'Noel José Gavarrete Martínez',
'Helene Gomez Alvarez',
'Jacqueline Del Rosario Gomez ',
'Estela Gomez Maria',
'Haryeri Nadeishda Gomez Ortiz',
'Marcos Antonio Gonzalez Delgado',
'Jose Abraham Gonzalez Diaz',
'Fernando Jose Gonzalez Gonzalez',
'Priscila Del Carmen Gonzalez Melendez',
'Karen Gonzalez Murillo',
'Gil Fernan Gonzalez Pallais',
'Shibel Lucia Gonzalez Rivera',
'Eduardo Cesar González González',
'Indiana González ',
'Dervin David Guevara Sirias',
'Karla Selene Guevara Solis',
'Nelson Orlando Guillen Machado',
'Salvador Gutierrez Buschting',
'Federico Vladimir Gutierrez Corea',
'Marlon Antonio Gutierrez Granja',
'Jean Carlos Gutierrez Gutierrez',
'Jose Sebastian Gutiérrez Carballo',
'Eddisson Francisco Hernandez',
'Patricio Jose Hernandez Bejarano',
'Carlos Alberto Hernandez Bojorge',
'Martha Clarisa Hernandez Chavez',
'Edbin Hernandez Gonzalez',
'Francisco Everth Hernandez Meneses',
'Fabiola De Jesus Hernandez Palacios',
'Carlos José Hernandez Ramirez',
'Keren Hernandez Reyes',
'Vladimiro Americo Herrera Americo',
'Vania Lizbeth Herrera Gonzalez',
'Marisol Herrera Toledo',
'Maria Del Socorro Herrera Vallejos',
'Ariel Herrera Vasquez',
'Marvin Hernan Herrera Vivas',
'Juan Rene Icaza Jimenez',
'Gladys Del Carmen Incer Rostran',
'Hans Jurgen Jahn ',
'Luis Alejandro Jarquin Pastora',
'Luis Alejandro Jerez Murillo',
'Esperanza Jiron Balladares',
'La Rocha Illiat Lennin Jiron De',
'Ivonne Dessiree Leyton Padilla',
'Jose Antonio Lezama',
'Glenda Valeria Lezama Solis',
'Ambrosia Del Carmen Lezama Zelaya',
'Mirna Lizeth Echaverry',
'Ingrid Yoamy Lopez Blandon',
'Ileana Margarita Lopez Briceño',
'Xilonen Lopez Calero',
'Indiana Lopez Castillo',
'Alvaro Lopez Castro',
'Nefi Antonio Lopez Garcia',
'Armando Jose Lopez Lopez',
'Oscar Lopez Meneses',
'Rudy Alberto Lopez Potosme',
'Tatiana María Lorenzo Curbelo',
'Marcelo Xavier Lugo Benedith',
'Freddy Luis López Barrios',
'Juana Mercedes López Cano',
'Karen Nadiesda López Sánchez',
'Guillermo Antonio Mairena Larios',
'Rosa Amanda Mairena Uriarte',
'Karla Elizabeth Malespin Garcia',
'Alvaro Cesar Malespin Miranda',
'Jose Alfonso Malta Videa',
'Jennifer Manzanarez Alvarado',
'Luis Marin Arguello',
'Cesar David Marin Lopez',
'Arlen Elisa Martinez Castro',
'Justina Martinez Castro',
'Martha Erica Martinez Gonzalez',
'Saslaya  Martinez Medrano',
'Sara Aida Martinez Parrales',
'Nohar Jose Martinez Rocha',
'Ileana Martinez Siles',
'Guadalupe De Los Angeles Martinez Valdivia',
'Manuel Martins Tavares',
'Roberto Jose Martínez Montes',
'Fernanda Marcela Matus Sobalvarro',
'Maria Elena Matute Ramirez',
'Maria Fernanda Maynard Sanchez',
'Maria Magdalena Mayorga Artola',
'Genesis Mayorga Castro',
'Tomasita Marcela Medina Cajina',
'Jose Enrique Medina Lopez',
'Jonathan Jose Medina Mongrio',
'Erika María Mejía Carcache',
'Rolando Jose Melendez Barrientos',
'Xochitl Idania Melendez Rivera',
'Nestor Membreño Argüello',
'Lester Antonio Membreño García',
'Ana Julia Mena Hernandez',
'Gabriela Rocio Mendieta Rodriguez',
'William Mendoza Cubillo',
'Carlos Alexander Mendoza Jacomino',
'Allan Alberto Mendoza Mercado',
'Irene Del Carmen Mercado Rodriguez',
'Carlos German Meza Gonzalez',
'Marcela Belen Miranda Cano',
'Braulio Miranda Castillo',
'Efren Andres Mogollon Montes',
'Claudio Mojica Valdez',
'Luis Alberto Molina Cuadra',
'Carlos Ernesto Moncada Pineda',
'Victor De Jesus Montalvan Hernandez',
'Cliford Jose Montalvan Narvaez',
'Margelia Fátima Montenegro Solórzano',
'Manuel Ernesto Montiel Silva',
'Sara De La Caridad Mora Grillo',
'Alejandro Mora Holmann',
'Tania Maria Mora Rocha',
'Karen Augusta Morales Gómez',
'Castalia Morales Jimenez',
'Moises Jeronimo Moreno Delgado',
'Lourdes Moreno Potosme',
'Leonor Eugenia Morin Muñoz',
'Eneyda Morraz Arauz',
'Jose Andres Munguia Cortez',
'Martha Lucia Murillo Soza',
'Alvaro Antonio Muñoz González',
'Carlos Hector Naranjo Iturralde',
'Karla Vanessa Narvaez Flores',
'Vernon Gabriel Narvaez Mairena',
'Nidome Gabriela',
'Moises Noguera Benavidez',
'Victor Manuel Noguera Zelaya',
'Johanna De Los Angeles Nuñez Sevilla',
'Carlos Francisco Obando Madrigal',
'Maria Denise Ocon Mora',
'Huber Ariel Oporta Benavidez',
'William Alexander Oporta Muntianu',
'Roberta Margarita Ortega Hernandez',
'Marvin Alejandro Ortiz Arias',
'Luis Manuel Osejo Pineda',
'Roger Gerardo Osorio Salazar',
'Karla Faviola Padilla Escobar',
'Pedro Armengol Palacio Narvaez',
'Vianey De Jesus Palacios Rivera',
'Giancarlo Paniagua Valerio',
'Osneily Esther Parajon Wong',
'Gerald Rafae Pentzke Chamorro',
'Marcos Tucapel Pereira Artola',
'Jennifer Pamela Perez Alonzo',
'Ramiro Perez Figueroa',
'May Rubby Leticia Perez Martinez',
'Alejandro Perez Rojas',
'Patricia Carolina Perez Serrano',
'Carlos Fidel Peña Orochena',
'Octavio Picado Garcia',
'Francisco Picado Linarte',
'Ana Lorena Picado Mayrena',
'Carolina Pineda Zeledon',
'Allan German Porras Chavez',
'Ramiro Fernando Pozo Urbina',
'Jhonny Rogelio Pérez Salazar',
'Alejandro Jose Quezada Ballesteros',
'Alberto Jose Quintanilla Tijerino',
'Belkis Ramirez Cano',
'Angela Ramos Obando',
'Fanny Reyes Castillo',
'Jefferson Manuel Reyes Ramos',
'Erick Saul Rios Juarez',
'Luis Horacio Rivas Cajina',
'Rivas Michael',
'Tania Ydith Rivas Morales',
'Maria Eunises Rivas Robleto',
'Alba Rivera Castillo',
'Maria Argentina Rivera Delgado',
'Jorge Rivera James',
'Norwin Ramon Rizo Picado',
'Haydeli Roa Lopez',
'Hazel Rodriguez Kerr',
'Jose David Rodriguez Larios',
'Yader Rodriguez Lopez',
'Derwis Jose Rodriguez Mejia',
'Maria Felix Rodriguez Palacios',
'Tania Del Socorro Rodriguez Palacios',
'Mario José Rodríguez Castillo',
'David Roy Rojas Rodriguez',
'Marielena Roman Frenzel',
'Rafael Antonio Roman Martinez',
'Eva Romano Urbina',
'Ana Valeria Romero Guido',
'Angelica Nadieshda Rosales Sandino',
'Reynalicia Rothschuh Davila',
'Jorge Alejandro Rugama Lopez',
'Guillermo Ernesto Ruiz Anduray',
'Eduviges De Los Angeles Ruiz Garcia',
'Ilce Ruiz Herrera',
'Guillermo Enrique Ruiz Tablada',
'Jessica Maria Saenz Gomez',
'Salasblanca Meryan',
'Erling Alfonso Salazar',
'Ethelmina Salazar Blandón',
'Blandon Marta Leonora Salazar De',
'Manuel Antonio Salgado Rios',
'Edgard Salinas Jimenez',
'Manuel De Jesus Sanchez Bonilla',
'Esdras Samuel Sanchez Trujillo',
'Jose Vidal Sandino Pavon',
'Thelma Del Carmen Sandoval Suazo',
'Joseph Uriel Sandy Rios',
'Armin Santamaria Cano',
'Olga Mayela Santamaria Rodriguez',
'Santamaría Tania',
'Norman Antonio Santana Urbina',
'Maria Lissette Selva Toruño',
'Ernesto Sequeira Enriquez',
'Jose Manuel Sequeira Hernandez',
'Jose Maria Silva Guzman',
'Mayron Sirias Martinez',
'Miriam Elizabeth Sirias Saldaña',
'Karina Solis Figueroa',
'Elizeth Carolina Solis Morales',
'Karla Vanessa Solorzano Blanco',
'Brissa Carmelina Suarez Bonilla',
'Carlos Shalem Suarez Borda',
'Yesbell Lisseth Talavera Galeano',
'Silvia Elena Tapia Blanco',
'Bolivar Francisco Tellez Castellon',
'Eneyda Jannine Tenorio Aburto',
'Silvia Gigdalia Ticay López',
'Maria Tijerino Zuniga',
'Gilda Tinoco Castillo',
'Sara Eugenia Toledo Balladares',
'Aracely Torres Arroliga',
'Hernan Antonio Torres Mendoza',
'Yubelkis Torres Rojas',
'Yara Torrez Blandon',
'Karen Astrid Traña Padilla',
'Rafael Angel Ubilla Suazo',
'Karla Ramona Urbina Davila',
'Anibal Urtecho Ortiz',
'Pedro Joaquin Valdivia Blandon',
'Tanya Walkyria Valenzuela Averruz',
'Perla Denisse Vallecillo Sanchez',
'Carlos Miguel Vanegas Benavides',
'Ana Lissette Vanegas Montes',
'Miguel Yasser Vargas Arias',
'Douglas Antonio Vasquez Espinoza',
'Marjorie Vanesa Vasquez Estrada',
'Karolinda Antonieta Vasquez Mejia',
'Joaquin Vega Montoya',
'Marvel Yomara Vegacruz Centeno',
'Marlon Jose Velasquez Reynoza',
'Mario Antonio Velez Ponce',
'Francisco Xavier Vivas Amador',
'Roberto Emilio Zacarías Díaz',
'Silvio Jose Zambrana Solano',
'Selena Cristina Zamora Mairena',
'Sergio Anibal Zapata Mendoza',
'Johanna Zelaya Gonzalez',
'Jose Alfredo Zelaya Hidalgo',
'Noe Zepeda Garcia',
'Marco Antonio Zepeda Noguera',
'Yuri Antonio Zepeda Orozco',
'Jhon Estiven Zuniga Hurtado',

            
        ];

        $role = Role::where('name', 'docente')->first();

        foreach ($docenteNames as $index => $name) {
            $user = User::create([
                'name' => $name,
                'email' => Str::slug($name, '.') . '@example.com',
                'password' => 'secret',
                'role_id' => $role?->id,
                'email_verified_at' => now(),
            ]);

            Docente::create([
                'usuario_id' => $user->id,
                'cif' => sprintf('25010%03d', $index + 1),
            ]);
        }
    }
}
